Feature/AffichagePion
CorentinDodon/Quoridor_4IRC pull request #16
Opened 2017-11-15 14:27 UTC by ubiklain

Gestion du déplacement des pions + positionnement des murs avec quelques règles pré-implémentées comme le chevauchement des murs impossible et la non sortie du plateau

2017-11-15 14:57 UTC, DuflotFlorian requested changes

2017-11-15 14:57 UTC, DuflotFlorian commented on src/vue/QuoridorGUI.java
> +        pion=null;
Pourquoi l’initialiser a null?

2017-11-15 14:57 UTC, DuflotFlorian commented on src/vue/QuoridorGUI.java
> +        return ((int) dim.getWidth() / 18);
Pourquoi la division par 18?

2017-11-15 14:57 UTC, DuflotFlorian commented on src/vue/QuoridorGUI.java
> +        //ajouter une barre en haut avec les informations qui vont bien
C'est un TODO ce commentaire?

2017-11-15 14:57 UTC, DuflotFlorian commented on src/vue/QuoridorGUI.java
> +        //this.setLayout(new BorderLayout());
Supprimer les commentaire inutiles

2017-11-15 14:57 UTC, DuflotFlorian commented on src/vue/QuoridorGUI.java
> +        getContentPane().setPreferredSize(dim);
Pourquoi utiliser setPreferredSize() plutot que setSize() ?

2017-11-15 14:57 UTC, DuflotFlorian commented on src/vue/QuoridorGUI.java
> +    public QuoridorGUI(String title, int taille) {
Que représente exactement taille ?

2017-11-15 14:57 UTC, DuflotFlorian commented on src/vue/QuoridorGUI.java
> +        //placement pions initiale
Utiliser une fonction pour cette partie d'init, car cela dépendra du nombre de joueurs

2017-11-15 14:57 UTC, DuflotFlorian commented on src/vue/QuoridorGUI.java
> +                    layeredPane.add(pion, JLayeredPane.DRAG_LAYER); //inverser deux niveau de layout // Exception à debug mais marche quand même
Met des TODO pour ne pas oublier les trucs a faire

2017-11-15 14:57 UTC, DuflotFlorian commented on src/vue/QuoridorGUI.java
> +                ImageIcon ic = new ImageIcon(new ImageIcon("images/PionNoir.png").getImage().getScaledInstance(tailleCasePion,tailleCasePion,Image.SCALE_DEFAULT));
Un peu étrange la classe ImageIcon qui instancie une classe ImageIcon pour s'instancier

2017-11-15 15:06 UTC, DuflotFlorian requested changes
Je n'ai absolument aucun pion qui s'affiche sur le plateau

>> il faut que tu change ton RootPath sur ton projet.  le notre est sur src/

@ubiklain @kev43 Dans ce genre de cas, il est bien de mettre a jour le fichier README afin d'en informer les utilisateurs 
UPDATE : J'ai fait les modifs et mis a jour le README pour cette partie

2017-11-15 15:06 UTC, DuflotFlorian commented on src/vue/QuoridorGUI.java
> +        /*beta en dur degeulasse*/
Supprime tes version beta degeulasse avant une PR.
Le but de la PR est d'avoir une version de develop propre et utilisable

2017-11-15 15:15 UTC, ubiklain commented on src/vue/QuoridorGUI.java
> +    public QuoridorGUI(String title, int taille) {
on va faire de la javadoc, mais dans l'idée taille c'est le nombre de case du plateau.

2017-11-15 15:17 UTC, ubiklain commented on src/vue/QuoridorGUI.java
> +        //ajouter une barre en haut avec les informations qui vont bien
oui, on va ajouter le TODO pour que ce soit plus visible dans l'IDE

2017-11-15 15:18 UTC, ubiklain commented on src/vue/QuoridorGUI.java
> +        //this.setLayout(new BorderLayout());
done

2017-11-15 15:22 UTC, ubiklain commented on src/vue/QuoridorGUI.java
> +        getContentPane().setPreferredSize(dim);
setPreferredSize() semble plus utilisé dans ce cas de figure. C'est du SWING et s'applique à un container.

setSize() s'applique a une dimension et c'est du AWT

2017-11-15 15:24 UTC, ubiklain commented on src/vue/QuoridorGUI.java
> +        //placement pions initiale
en attente de refacto.  cette partie devrait etre gérée par le Controller amha.

à voir comment on s'accorde avec vous et votre backend

2017-11-15 15:25 UTC, ubiklain commented on src/vue/QuoridorGUI.java
> +                ImageIcon ic = new ImageIcon(new ImageIcon("images/PionNoir.png").getImage().getScaledInstance(tailleCasePion,tailleCasePion,Image.SCALE_DEFAULT));
cela permet de resizer les images à la bonne taille

2017-11-15 15:28 UTC, ubiklain commented on src/vue/QuoridorGUI.java
> +                    layeredPane.add(pion, JLayeredPane.DRAG_LAYER); //inverser deux niveau de layout // Exception à debug mais marche quand même
le commentaire était obsolete, il sera viré au prochain commit

2017-11-15 15:29 UTC, ubiklain commented on src/vue/QuoridorGUI.java
> +        return ((int) dim.getWidth() / 18);
c'est le meilleur rapport taille ecran en INT

2017-11-15 15:30 UTC, ubiklain commented on src/vue/QuoridorGUI.java
> +        return ((int) dim.getWidth() / 18);
commentaire ajouté dans le code pour plus de clarté

2017-11-15 15:31 UTC, ubiklain commented on src/vue/QuoridorGUI.java
> +        /*beta en dur degeulasse*/
ok

2017-11-15 16:06 UTC, CorentinDodon commented
Par contre la prochaine fois faites des pull request quand on vous le demande et pas une au bout de 3semaines avec 20 commit, une pull request c'est une fonctionnalité pas plusieurs, c'est hyper chiant à review apres quand vous nous chiez autant de code comme ca

2017-11-15 16:13 UTC, ubiklain commented
toutes nos modifs sont push sur affivchagePion, vous pouvez les revalider.

kevin & ludo

2017-11-16 18:39 UTC, DuflotFlorian commented on src/vue/QuoridorGUI.java
> +    public QuoridorGUI(String title, int taille) {
Dans ce cas la, peut etre qu'il vaut mieux le renommer nbCases ou quelque chose du genre

2017-11-16 19:13 UTC, DuflotFlorian approved these changes

2017-11-17 11:01 UTC, merged