Feature/fill panel cote
CorentinDodon/Quoridor_4IRC pull request #27
Opened 2017-12-21 21:18 UTC by kev43

Affichage des infos des joueurs sur le coté. Toute la partie style est faite, il faut juste interconnecter avec le back.

2017-12-22 10:14 UTC, DuflotFlorian requested changes

2017-12-22 10:14 UTC, DuflotFlorian commented on src/vue/QuoridorGUI.java
> +        //garageMurGauche.setBackground(Color.GREEN);
Enleve les commentaires inutiles

2017-12-22 10:14 UTC, DuflotFlorian commented on src/vue/QuoridorGUI.java
> +        //garageMurDroit.setBackground(Color.BLUE);
commentaire a enlever

2017-12-22 10:14 UTC, DuflotFlorian commented on src/vue/QuoridorGUI.java
> +        //plateauQuoridor.setBorder(BorderFactory.createLineBorder(Color.BLACK ,2));
commentaire a enlever

2017-12-22 10:14 UTC, DuflotFlorian commented on src/vue/QuoridorGUI.java
> +                    //update();
commentaire a enlever

2017-12-22 10:14 UTC, DuflotFlorian commented on src/vue/QuoridorGUI.java
> +                    //update();
commentaire a enlever

2017-12-22 10:14 UTC, DuflotFlorian commented on src/vue/QuoridorGUI.java
> +    private void remplissagePanelCote (/*TODO passer la liste des joueurs IHM*/) {
Je ne peux pas accepter ta PR avec des TODO, il faudra que tu y fasse les modifications pour enlever les TODO

2017-12-22 10:14 UTC, DuflotFlorian commented on src/vue/QuoridorGUI.java
> +        garageMurDroit.setBackground(Color.PINK);
Pourquoi changer la couleur du background ligne 98 pour les re changer maintenant? Un des 2 est de trop

2017-12-22 10:14 UTC, DuflotFlorian commented on src/vue/QuoridorGUI.java
> +        int nbRowInColumn = 0;
Que représente exactement cette int? N'hesite pas a le mettre en commentaire

2017-12-22 10:14 UTC, DuflotFlorian commented on src/vue/QuoridorGUI.java
> +            tabPanelGauche[i][0].setBackground(new Color(404040));
Pourquoi utiliser une couleur en hexa maintenant? Au minimum précise la couleur en commentaire
Ici pour un gris, je ne pense pas que ce soit nécessaire de passer par l'hexa

2017-12-22 10:14 UTC, DuflotFlorian commented on src/vue/QuoridorGUI.java
> +        /*TODO GetCurrentPlayer*/
IDEM, TODO a faire avant merge

2017-12-22 10:51 UTC, kev43 commented on src/vue/QuoridorGUI.java
> +            tabPanelGauche[i][0].setBackground(new Color(404040));
Utilisation de code hexa, car plus nuances non disponnibles avec des macros de type Color.RED.
J'ajoute un comentaire avec la couleur

2017-12-22 11:03 UTC, kev43 commented
J'ai fait les modifs.
ça doit être bon

2017-12-22 12:41 UTC, kev43 commented
J'ai fait les modifs demandées.

Le 22 décembre 2017 à 11:14, DuflotFlorian <notifications@github.com> a
écrit :

> *@DuflotFlorian* requested changes on this pull request.
> ------------------------------
>
> In src/vue/QuoridorGUI.java
> <https://github.com/DuflotFlorian/Quoridor_4IRC/pull/27#discussion_r158461944>
> :
>
> > @@ -79,14 +87,16 @@ public QuoridorGUI(String title, int taille) {
>          layeredPane.add(garageMurGauche, JLayeredPane.DEFAULT_LAYER);
>          garageMurGauche.setPreferredSize(new Dimension(tailleLargeurGarageMur , tailleIHMHauteur));
>          garageMurGauche.setBounds(0, 0, tailleLargeurGarageMur, tailleIHMHauteur);
> -        garageMurGauche.setBackground(Color.GREEN);
> +        //garageMurGauche.setBackground(Color.GREEN);
>
> Enleve les commentaires inutiles
> ------------------------------
>
> In src/vue/QuoridorGUI.java
> <https://github.com/DuflotFlorian/Quoridor_4IRC/pull/27#discussion_r158461971>
> :
>
> >
>          //Creation du stockage à murs gauche
>          garageMurDroit = new JPanel();
>          layeredPane.add(garageMurDroit, JLayeredPane.DEFAULT_LAYER);
>          garageMurDroit.setPreferredSize(new Dimension(tailleLargeurGarageMur , tailleIHMHauteur));
>          garageMurDroit.setBounds(taillePlateauQuoridor+tailleLargeurGarageMur, 0, tailleLargeurGarageMur, tailleIHMHauteur);
> -        garageMurDroit.setBackground(Color.BLUE);
> +        //garageMurDroit.setBackground(Color.BLUE);
>
> commentaire a enlever
> ------------------------------
>
> In src/vue/QuoridorGUI.java
> <https://github.com/DuflotFlorian/Quoridor_4IRC/pull/27#discussion_r158462008>
> :
>
> > @@ -153,9 +163,12 @@ public QuoridorGUI(String title, int taille) {
>              }
>          }
>
> +        //plateauQuoridor.setBorder(BorderFactory.createLineBorder(Color.BLACK ,2));
>
> commentaire a enlever
> ------------------------------
>
> In src/vue/QuoridorGUI.java
> <https://github.com/DuflotFlorian/Quoridor_4IRC/pull/27#discussion_r158462037>
> :
>
> > @@ -224,11 +237,12 @@ public void mouseReleased(MouseEvent e) {
>                      Container parent = (Container) cmp;
>                      parent.add(pion);
>                      pion.setVisible(true);
> -                    update();
> +                    //update();
>
> commentaire a enlever
> ------------------------------
>
> In src/vue/QuoridorGUI.java
> <https://github.com/DuflotFlorian/Quoridor_4IRC/pull/27#discussion_r158462053>
> :
>
> >                  }
>                  else {
> -                    update();
> +                    //update();
>
> commentaire a enlever
> ------------------------------
>
> In src/vue/QuoridorGUI.java
> <https://github.com/DuflotFlorian/Quoridor_4IRC/pull/27#discussion_r158462316>
> :
>
> > @@ -440,4 +454,74 @@ private void affichePion(Coordonnees coord, Couleur c) {
>          JLabel piece = new JLabel(new ImageIcon(imageURL));
>          j.add(piece);
>      }
> +
> +
> +    private void remplissagePanelCote (/*TODO passer la liste des joueurs IHM*/) {
>
> Je ne peux pas accepter ta PR avec des TODO, il faudra que tu y fasse les
> modifications pour enlever les TODO
> ------------------------------
>
> In src/vue/QuoridorGUI.java
> <https://github.com/DuflotFlorian/Quoridor_4IRC/pull/27#discussion_r158462474>
> :
>
> > @@ -440,4 +454,74 @@ private void affichePion(Coordonnees coord, Couleur c) {
>          JLabel piece = new JLabel(new ImageIcon(imageURL));
>          j.add(piece);
>      }
> +
> +
> +    private void remplissagePanelCote (/*TODO passer la liste des joueurs IHM*/) {
> +        /*TODO Count nombre de joueurs pour les afficher sur les cotés*/
> +        int nbPlayer = 4 ; //Utiliser la liste des joueurs au lieu de la valmeur en dur
> +        int nbRowInColumn = 0;
> +
> +
> +        garageMurDroit.setBackground(Color.PINK);
>
> Pourquoi changer la couleur du background ligne 98 pour les re changer
> maintenant? Un des 2 est de trop
> ------------------------------
>
> In src/vue/QuoridorGUI.java
> <https://github.com/DuflotFlorian/Quoridor_4IRC/pull/27#discussion_r158462581>
> :
>
> > @@ -440,4 +454,74 @@ private void affichePion(Coordonnees coord, Couleur c) {
>          JLabel piece = new JLabel(new ImageIcon(imageURL));
>          j.add(piece);
>      }
> +
> +
> +    private void remplissagePanelCote (/*TODO passer la liste des joueurs IHM*/) {
> +        /*TODO Count nombre de joueurs pour les afficher sur les cotés*/
> +        int nbPlayer = 4 ; //Utiliser la liste des joueurs au lieu de la valmeur en dur
> +        int nbRowInColumn = 0;
>
> Que représente exactement cette int? N'hesite pas a le mettre en
> commentaire
> ------------------------------
>
> In src/vue/QuoridorGUI.java
> <https://github.com/DuflotFlorian/Quoridor_4IRC/pull/27#discussion_r158462790>
> :
>
> > +        JPanel [][] tabPanelDroit = null;
> +
> +        if (nbPlayer == 2) {
> +            nbRowInColumn = 3;
> +
> +        } else if (nbPlayer == 4) {
> +            nbRowInColumn = 5;
> +        }
> +
> +        garageMurGauche.setLayout(new GridLayout(nbRowInColumn,1));
> +        garageMurDroit.setLayout(new GridLayout(nbRowInColumn,1));
> +
> +        tabPanelGauche = new JPanel[nbRowInColumn][1];
> +        for (int i =0 ; i<nbRowInColumn ; i++) {
> +            tabPanelGauche[i][0] = new JPanel();
> +            tabPanelGauche[i][0].setBackground(new Color(404040));
>
> Pourquoi utiliser une couleur en hexa maintenant? Au minimum précise la
> couleur en commentaire
> Ici pour un gris, je ne pense pas que ce soit nécessaire de passer par
> l'hexa
> ------------------------------
>
> In src/vue/QuoridorGUI.java
> <https://github.com/DuflotFlorian/Quoridor_4IRC/pull/27#discussion_r158462867>
> :
>
> > +        }
> +
> +        if(nbPlayer==2) {
> +            createLabelCote(tabPanelGauche[1][0],1);
> +            createLabelCote(tabPanelDroit[1][0],2);
> +
> +        } else if (nbPlayer == 4){
> +            createLabelCote(tabPanelGauche[1][0],1);
> +            createLabelCote(tabPanelDroit[1][0],2);
> +            createLabelCote(tabPanelGauche[3][0],3);
> +            createLabelCote(tabPanelDroit[3][0],4);
> +        }
> +    }
> +
> +    private void createLabelCote (JPanel jp, int numJoueur) {
> +        /*TODO GetCurrentPlayer*/
>
> IDEM, TODO a faire avant merge
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/DuflotFlorian/Quoridor_4IRC/pull/27#pullrequestreview-85277847>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AFepaR4MkwhMuZFijDLxybmC_GOhFexAks5tC4EXgaJpZM4RKXV6>
> .
>

2017-12-28 12:31 UTC, DuflotFlorian requested changes

2017-12-28 12:31 UTC, DuflotFlorian commented on src/vue/QuoridorGUI.java
> +                    update(); //Ligne a commenter pour debug, permet au pion de ne pas toujours revenir à sa position intiale
Cela n'a aucun sens. Ca veut dire que sur la version fonctionnelle, le pion reviens toujours à sa position initiale?

2017-12-28 12:32 UTC, DuflotFlorian commented
Quand je dit d'enlever un TODO ca ne veut pas dire de le supprimer, mais de le faire...

2017-12-28 15:12 UTC, kev43 commented on src/vue/QuoridorGUI.java
> +                    update(); //Ligne a commenter pour debug, permet au pion de ne pas toujours revenir à sa position intiale
Done. Ce n'était plus utile

2017-12-28 15:14 UTC, kev43 commented
Les TODO sont faits.
Pour faire cela j'ai du merge la branche update2.0 dans ma branche car j'avais besoin des fonctions du back pour faire quelque chose de fonctionnel.

La gestion du nombre de murs affiché sera mis à jour avec la gestion des murs coté back.

2017-12-29 02:08 UTC, DuflotFlorian commented
Ba non Kevin, il ne faut pas faire ca.
Regarde ce site https://danielkummer.github.io/git-flow-cheatsheet/
Il t'expliquera comment utiliser de la bonne manière les branches Git

2017-12-29 17:09 UTC, kev43 commented
J'ai revert mon merge.
J'ai rebase mes commits à partir du devellop actuel pour obtenir quelque chose de testable.

Normalement ça peut se merge dans develop.
Ce coup-ci je pense avoir tout vérifié et ne pas avoir fait d'erreur à cause de mon niveau moisi en Git.

2018-01-04 16:00 UTC, merged