adaptation de l'ENUM quoridorColor :
CorentinDodon/Quoridor_4IRC pull request #46
Opened 2018-01-10 15:06 UTC by ubiklain

> donne un nom français au joueur et est accessible via des accesseurs
 > colorise le texte et l'encadrement du joueur courant avec la même couleur que le pion choppé à la pipette

2018-01-10 15:24 UTC, DuflotFlorian commented on src/Class/QuoridorColor.java
> +    private Color color_box;
Utilisation du camelCase plutot que du underscore

2018-01-10 15:24 UTC, DuflotFlorian commented on src/Class/QuoridorColor.java
> +    public Color getColor_box() {
camelCase pour le nom de la fonction

2018-01-10 16:19 UTC, ubiklain commented on src/Class/QuoridorColor.java
> +    private Color color_box;
ok

2018-01-10 16:19 UTC, ubiklain commented on src/Class/QuoridorColor.java
> +    public Color getColor_box() {
ok

2018-01-11 09:39 UTC, DuflotFlorian requested changes

2018-01-11 09:39 UTC, DuflotFlorian commented on src/Class/QuoridorColor.java
> +    public void setColorBox(Color color_box) {
A mettre aussi en camelCase pour le nom de la variable

2018-01-11 20:51 UTC, ubiklain commented
ok

2018-01-15 13:16 UTC, DuflotFlorian commented on src/Class/QuoridorColor.java
> +    private JLabel playerName;
Tu va dire que je m’arrête sur des détails :) mais je ne suis pas fan du nom de ton JLabel.
On ne sais pas vraiment que c'est un JLabel dans le nom, ce qui porte a confusion.
Je pense que refactore le "playerName" en "JLabelPlayerName" serait plus approprié.

2018-01-15 13:16 UTC, DuflotFlorian commented on src/Class/QuoridorColor.java
> +    public JLabel getPlayerName() {
Du coup du fait du refacto, le "getPlayerName" devient "getJLabelPlayerName"

2018-01-15 13:16 UTC, DuflotFlorian commented on src/vue/QuoridorGUI.java
> +        JLabel playerName = currentPlayerColor.getPlayerName();
Le refacto de l'enum rend cette fonction plus clair avec le "getJLabelPlayerName".
On comprend au premier coup d'oeil que c'est bien un JLabel que l'on récupère et pas un String ou autre :)

2018-01-15 15:42 UTC, ubiklain commented
corrections aux review apportés

2018-01-16 15:12 UTC, DuflotFlorian approved these changes

2018-01-16 15:13 UTC, merged