fixBug des lignes blanches qui apparaissent dans les panneaux de côté…
CorentinDodon/Quoridor_4IRC pull request #48
Opened 2018-01-10 16:16 UTC by ubiklain

fixBug des lignes blanches qui apparaissent dans les panneaux de côté selon la résolution de l'écran

2018-01-11 09:42 UTC, DuflotFlorian requested changes

2018-01-11 09:42 UTC, DuflotFlorian commented on src/vue/QuoridorGUI.java
> +        // ABkr 4
Que signifie ce commentaire?

2018-01-11 09:42 UTC, DuflotFlorian commented on src/vue/QuoridorGUI.java
> +        // troisZones.add(boardQuoridor, BorderLayout.CENTER);
Enlever le com qui ne sert à rien

2018-01-11 09:42 UTC, DuflotFlorian commented on src/vue/QuoridorGUI.java
> +            tabRightPanel[i][0].setBackground(this.backgroundColor); //Bleu-Nuit
Enlever le com bleu nuit

2018-01-11 09:42 UTC, DuflotFlorian commented on src/vue/QuoridorGUI.java
>              panelInfoLeft.add(tabLeftPanel[i][0]);
Enlever le commentaire bleu nuit

2018-01-11 20:35 UTC, ubiklain commented on src/vue/QuoridorGUI.java
> +        // ABkr 4
C'est un résidu d'une tentative du prof de régler votre bug d'affichage.
je l'efface.

2018-01-11 20:35 UTC, ubiklain commented on src/vue/QuoridorGUI.java
> +        // troisZones.add(boardQuoridor, BorderLayout.CENTER);
ok

2018-01-11 20:36 UTC, ubiklain commented on src/vue/QuoridorGUI.java
>              panelInfoLeft.add(tabLeftPanel[i][0]);
ok

2018-01-11 20:36 UTC, ubiklain commented on src/vue/QuoridorGUI.java
> +            tabRightPanel[i][0].setBackground(this.backgroundColor); //Bleu-Nuit
ok

2018-01-11 20:48 UTC, ubiklain commented
commentaires supprimés

2018-01-15 13:17 UTC, DuflotFlorian approved these changes

2018-01-15 13:18 UTC, merged